import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./components/ui/NavBar";
import Footer from "./components/ui/Footer";
import AuthSessionProvider from "./components/providers/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, route1, route2 }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthSessionProvider>
          <NavBar />
          {children}
          {route1}
          {route2}
        </AuthSessionProvider>
          <Footer />
      </body>
    </html>
  );
}
